[package]
name = "recursive_verifier"
version = "0.1.0"
edition = "2024_07"

[dependencies]
stwo_cairo_air = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "ccd15a48d1d1d732bdb8a1e1e769600623896f00" }
stwo_verifier_core = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "ccd15a48d1d1d732bdb8a1e1e769600623896f00" }
cairo_execute = "2.9.2"

[executable]

[lib]

[profile.profiling]
unstable-add-statements-functions-debug-info = true
unstable-add-statements-code-locations-debug-info = true

[profile.proving]
inherits = "release"

[profile.proving.cairo]
enable-gas = false

[dev-dependencies]
cairo_test = "2.9.2"
