name: AggSig Checker Cairo

on:
  push:
    branches: [ main ]
  pull_request:

permissions: read-all

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Scarb
        uses: software-mansion/setup-scarb@v1.3.2

      - name: Check formatting
        run: scarb fmt --check
        working-directory: packages/aggsig_checker

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Install Scarb
        uses: software-mansion/setup-scarb@v1.3.2

      - name: Run tests
        run: make test
        working-directory: packages/aggsig_checker

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Scarb
        uses: software-mansion/setup-scarb@v1.3.2
        with:
          scarb-version: "nightly"

      - name: Build project for proving
        run: make build
        working-directory: packages/aggsig_checker
